benchmark:
  name: "ruler"
  framework: "lm_eval"

evaluation:
  tasks: "ruler"
  batch_size: 1
  num_samples: 65
  max_seq_lengths:
    - 4096
    - 8192
    - 16384
    - 32768
    - 65536
    - 131072

output:
  dir: "results/evaluations/llm/ruler"
